version: '3.0'
services:
  api:
    build: ./
    command: ["wait-for-it", "db:5432", "--", "npm", "run", "dev"]
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:10
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: development_db

